cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      use-default-aws-credentials-chain: true

app:
  s3:
    bucket: ${S3_BUCKET_NAME:your-amplify-bucket}

server:
  port: ${PORT:8080}
